ODMC_exam_implementation/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

# Add URL maps to redirect the base URL to our application
from .views import HomePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home'),
    path('spacemissions/', include('space_missions.urls', namespace='space_missions')),
]

space_missions/urls.py
from django.urls import path
from . import views

app_name = 'space_missions'

urlpatterns = [
    path('countries-metadata/', views.CountryMetadata.as_view(), name='countries'),
    path('countries/', views.CountryList.as_view(), name='countries-list'),
    path('country/<int:pk>/', views.CountryDetail.as_view(), name='country-detail'),
    path('countries/download-csv', views.download_countries_csv, name='countries-csv'),
    path('astronauts-metadata/', views.AstronautMetadata.as_view(), name='astronauts'),
    path('astronauts/', views.AstronautList.as_view(), name='astronauts-list'),
    path('astronaut/<int:pk>/', views.AstronautDetail.as_view(), name='astronaut-detail'),
    path('astronauts/download-csv', views.download_astronauts_csv, name='astronauts-csv'),
    path('astronautsoccupations/download-csv', views.download_astronaut_occupations_csv, name='astronautoccupations-csv'),
    path('astronautsselections/download-csv', views.download_astronauts_selections_csv, name='astroanutsselections-csv'),
    path('organisations-metadata/', views.OrganisationMetadata.as_view(), name='organisations'),
    path('organisations/', views.OrganisationList.as_view(), name='organisations-list'),
    path('organisation/<int:pk>/', views.OrganisationDetail.as_view(), name='organisation-detail'),
    path('organisations/download-csv', views.download_organisations_csv, name='organisation-csv'),
    path('engines-metadata/', views.EngineMetadata.as_view(), name='engines'),
    path('engines/', views.EngineList.as_view(), name='engines-list'),
    path('engine/<int:pk>/', views.EngineDetail.as_view(), name='engine-detail'),
    path('engines/download-csv', views.download_engines_csv, name='engines-csv'),
    path('stages-metadata/', views.StageMetadata.as_view(), name='stages'),
    path('stages/', views.StageList.as_view(), name='stages-list'),
    path('stage/<int:pk>/', views.StageDetail.as_view(), name='stage-detail'),
    path('stages/download-csv', views.download_stages_csv, name='stages-csv'),
    path('launchvehicles-metadata/', views.LaunchVehicleMetadata.as_view(), name='launch-vehicles'),
    path('launchvehicles/', views.LaunchVehicleList.as_view(), name='launch-vehicles-list'),
    path('launchvehicle/<int:pk>/', views.LaunchVehicleDetail.as_view(), name='launch-vehicle-detail'),
    path('launchvehicles/download-csv', views.download_launch_vehicles_csv, name='launchvehicles-csv'),
    path('vehiclestages/download-csv', views.download_vehicle_stages_csv, name='vehiclestages-csv'),
    path('missions-launches-metadata/', views.MissionAndLaunchMetadata.as_view(), name='missions'),
    path('missions/', views.MissionList.as_view(), name='missions-list'),
    path('mission/<int:pk>/', views.MissionDetail.as_view(), name='mission-detail'),
    path('missions/download-csv', views.download_missions_csv, name='missions-csv'),
    path('selections-metadata/', views.SelectionMetadata.as_view(), name='selections'),
    path('selections/', views.SelectionList.as_view(), name='selections-list'),
    path('selection/<int:pk>/', views.SelectionDetail.as_view(), name='selection-detail'),
    path('selections/download-csv', views.download_selections_csv, name='selections-csv'),
]

space_missions/views.py
# Create your views here.
import csv

from django.http import HttpResponse
from django.views import generic
from . import models
from .models import Organisation, Country, Astronaut, Engine, LaunchVehicle, VehicleStage, Mission, AstronautOccupation, \
    Selection, AstronautSelection, Stage


class CountryList(generic.ListView):
    paginate_by = 20
    model = models.Country


class CountryDetail(generic.DetailView):
    model = models.Country


class AstronautList(generic.ListView):
    paginate_by = 20
    model = models.Astronaut


class AstronautDetail(generic.DetailView):
    model = models.Astronaut


class OrganisationDetail(generic.DetailView):
    model = models.Organisation


class OrganisationList(generic.ListView):
    paginate_by = 20
    model = models.Organisation


class EngineList(generic.ListView):
    paginate_by = 20
    model = models.Engine


class EngineDetail(generic.DetailView):
    model = models.Engine


class StageDetail(generic.DetailView):
    model = models.Stage


class StageList(generic.ListView):
    paginate_by = 20
    model = models.Stage


class LaunchVehicleList(generic.ListView):
    paginate_by = 20
    model = models.LaunchVehicle


class LaunchVehicleDetail(generic.DetailView):
    model = models.LaunchVehicle


class MissionList(generic.ListView):
    paginate_by = 20
    model = models.Mission


class MissionDetail(generic.DetailView):
    model = models.Mission


class SelectionList(generic.ListView):
    paginate_by = 20
    model = models.Selection


class SelectionDetail(generic.DetailView):
    model = models.Selection


metadata_url = 'space_missions/metadata/'


class AstronautMetadata(generic.TemplateView):
    template_name = metadata_url + 'astronaut.html'


class CountryMetadata(generic.TemplateView):
    template_name = metadata_url + 'country.html'


class EngineMetadata(generic.TemplateView):
    template_name = metadata_url + 'engine.html'


class LaunchVehicleMetadata(generic.TemplateView):
    template_name = metadata_url + 'launch_vehicle.html'


class MissionAndLaunchMetadata(generic.TemplateView):
    template_name = metadata_url + 'launch_mission.html'


class OrganisationMetadata(generic.TemplateView):
    template_name = metadata_url + 'organisation.html'


class SelectionMetadata(generic.TemplateView):
    template_name = metadata_url + 'selection.html'


class StageMetadata(generic.TemplateView):
    template_name = metadata_url + 'stage.html'


def download_organisations_csv(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="organisations.csv"'}
    )
    writer = csv.writer(response)
    writer.writerow(['code', 'name', 'english_name', 'location',
                     'country', 'longitude', 'latitude', 'parent_organisation']
                    )
    for organisation in Organisation.objects.all():
        parent_organisation = None if organisation.parent_organisation is None else organisation.parent_organisation.code
        country = None if organisation.country is None else organisation.country.code
        writer.writerow([organisation.code, organisation.name,
                         organisation.english_name, organisation.location,
                         country, organisation.longitude, organisation.latitude,
                         parent_organisation])
    return response


def download_countries_csv(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="countries.csv"'}
    )
    writer = csv.writer(response)
    writer.writerow(['code', 'name', 'continent'])
    for country in Country.objects.all():
        writer.writerow([country.code, country.name, country.continent])

    return response


def download_astronauts_csv(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="astronauts.csv"'}
    )
    writer = csv.writer(response)
    writer.writerow(['name', 'original_name', 'sex', 'background', 'birth_year', 'nationality'])
    for astronaut in Astronaut.objects.all():
        nationality = None if astronaut.nationality is None else astronaut.nationality.code
        writer.writerow([astronaut.name, astronaut.original_name, astronaut.get_sex_display(),
                         astronaut.get_background_display(), astronaut.birth_year,
                         nationality])

    return response


def download_engines_csv(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="engines.csv"'}
    )
    writer = csv.writer(response)
    writer.writerow(['name', 'manufacturer', 'mass', 'impulse', 'thrust', 'isp',
                     'burn_duration', 'chambers'])
    for engine in Engine.objects.all():
        manufacturer = None if engine.manufacturer is None else engine.manufacturer.code
        writer.writerow([engine.name, manufacturer, engine.mass,
                         engine.impulse, engine.thrust, engine.isp,
                         engine.burn_duration, engine.chambers])

    return response


def download_launch_vehicles_csv(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="LaunchVehicles.csv"'}
    )
    writer = csv.writer(response)
    writer.writerow(['name', 'min_stage', 'max_stage', 'launch_mass', 'TO_thrust',
                     'length', 'diameter', 'vehicle_class', 'manufacturer'])

    for vehicle in LaunchVehicle.objects.all():
        manufacturer = None if vehicle.manufacturer is None else vehicle.manufacturer.code
        writer.writerow([vehicle.name, vehicle.min_stage, vehicle.max_stage,
                         vehicle.launch_mass, vehicle.TO_thrust,
                         vehicle.length, vehicle.diameter, vehicle.get_vehicle_class_display(),
                         manufacturer])

    return response


def download_vehicle_stages_csv(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="VehicleStages.csv"'}
    )
    writer = csv.writer(response)
    writer.writerow(['launch_vehicle', 'stage', 'stage_number', 'dummy'])

    for vehicle_stage in VehicleStage.objects.all():
        writer.writerow([vehicle_stage.launch_vehicle.name, vehicle_stage.stage.name,
                         vehicle_stage.get_stage_number_display(),
                         vehicle_stage.dummy])

    return response


def download_missions_csv(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="Missions.csv"'}
    )
    writer = csv.writer(response)
    writer.writerow(['name', 'launch_id', 'date', 'launch_vehicle', 'organisation',
                     'success_or_fail', 'launch_type'])

    for mission in Mission.objects.all():
        launch_id = None if mission.launch is None else mission.launch.launch_id
        launch_date = None if mission.launch is None else mission.launch.date
        vehicle = None if mission.launch.launch_vehicle is None else mission.launch.launch_vehicle.name
        organisation = None if mission.launch.organisation is None else mission.launch.organisation.code
        writer.writerow([mission.name, launch_id, launch_date,
                         vehicle, organisation,
                         mission.launch.launch_type])

    return response


def download_astronaut_occupations_csv(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="AstronautOccupations.csv"'}
    )
    writer = csv.writer(response)
    writer.writerow(['astronaut', 'mission', 'role', 'join_year'])

    for astronaut_occupation in AstronautOccupation.objects.all():
        writer.writerow([astronaut_occupation.astronaut.name,
                         astronaut_occupation.mission.name,
                         astronaut_occupation.role, astronaut_occupation.join_year])

    return response


def download_selections_csv(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="selections.csv"'}
    )
    writer = csv.writer(response)
    writer.writerow(['name', 'mission'])

    for selection in Selection.objects.all():
        for mission in selection.missions.all():
            writer.writerow([selection.name, mission.name])

    return response


def download_astronauts_selections_csv(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="AstronautsSelections.csv"'}
    )
    writer = csv.writer(response)
    writer.writerow(['astronaut', 'selection', 'selection_year'])

    for astronaut_selection in AstronautSelection.objects.all():
        writer.writerow([astronaut_selection.astronaut.name, astronaut_selection.selection.name,
                         astronaut_selection.selection_year])
    return response


def download_stages_csv(request):
    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="Stages.csv"'}
    )
    writer = csv.writer(response)
    writer.writerow(['name', 'dry_mass', 'launch_mass', 'thrust', 'burn_duration',
                     'length', 'diameter', 'engine', 'manufacturer'])

    for stage in Stage.objects.all():
        manufacturer = None if stage.manufacturer is None else stage.manufacturer.code
        engine = None if stage.engine is None else stage.engine.name
        writer.writerow([stage.name, stage.dry_mass, stage.launch_mass, stage.thrust,
                         stage.burn_duration, stage.length, stage.diameter, engine,
                         manufacturer])
    return response

templates/space_missions/metadata/astronaut.html
{% extends 'base.html' %}

{% block content %}
    <h1>Astronaut Metadata</h1>
    <ul>
        <li><strong>Full Name:</strong> the full name of the astronaut, more precisely "<em>surname, name</em>".</li>
        <li><strong>Birth year:</strong> the birth year of the astronaut.</li>
        <li><strong>Sex:</strong> the astronaut biological sex, might be unspecified.</li>
        <li><strong>Background: </strong>military, civilian or unspecified.</li>
        <li>
            <strong>Nationality: </strong>code
            <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">
                ISO 3166-1 alpha-2
            </a> that refers to the <a href="{% url 'space_missions:countries' %}">Country</a> table
        </li>
    </ul>
    <h2>Data</h2>
    <ul>
        <li><a href="{% url 'space_missions:astronauts-list' %}">Click here to view the list of all astronauts</a></li>
        <li><a href="{% url 'space_missions:astronauts-csv' %}">Click here to download the data in csv format</a></li>
    </ul>
{% endblock %}

templates/space_missions/metadata/country.html
{% extends 'base.html' %}

{% block content %}
    <h1>Country Metadata</h1>
    <ul>
        <li><strong>Code:</strong> the country <a href="https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">
                ISO 3166-1 alpha-2
            </a> code.
        </li>
        <li><strong>Name:</strong> the country name.</li>
        <li><strong>Continent: </strong> the continent name, the possible values are <em>Africa, Americas, Asia, Europe, Oceania, Antarctica.</em></li>
    </ul>
    <h2>Data</h2>
    <ul>
        <li><a href="{% url 'space_missions:countries-list' %}">Click here to view the list of the countries.</a></li>
        <li><a href="{% url 'space_missions:countries-csv' %}">Click here to download the country data in csv format.</a></li>
    </ul>
{% endblock %}

templates/space_missions/metadata/engine.html
{% extends 'base.html' %}

{% block content %}
    <h1>Engine Metadata</h1>
    <ul>
        <li><strong>Name:</strong> the name of the engine, given by the <a href="{% url 'space_missions:organisations' %}">manufacturer</a></li>
        <li><strong>Manufacturer:</strong> the code of the <a href="{% url 'space_missions:organisations' %}">organisation</a> that manufactured the engine.</li>
        <li><strong><a href="https://en.wikipedia.org/wiki/Mass">Mass</a>: </strong> the <a href="https://en.wikipedia.org/wiki/Mass">mass</a> in Kg of the engine.</li>
        <li><strong><a href="https://en.wikipedia.org/wiki/Impulse_(physics)">Impulse</a>: </strong> the <a href="https://en.wikipedia.org/wiki/Impulse_(physics)">impulse</a> of the engine, expressed in <a href="https://en.wikipedia.org/wiki/Newton_(unit)#:~:text=Commonly%20seen%20as%20kilonewtons,
                -It%20is%20common&text=One%20kilonewton%2C%201%20kN%2C%20is,%C3%97%209.81%20m%2Fs2.">kN</a>/s.</li>
        <li>
            <strong>
                <a href="https://en.wikipedia.org/wiki/Thrust">Thrust</a>:
            </strong>
                the <a href="https://en.wikipedia.org/wiki/Thrust">thrust</a> of the engine, expressed in
                <a href="https://en.wikipedia.org/wiki/Newton_(unit)#:~:text=Commonly%20seen%20as%20kilonewtons,
                -It%20is%20common&text=One%20kilonewton%2C%201%20kN%2C%20is,%C3%97%209.81%20m%2Fs2.">kN</a>
        </li>
        <li><strong><a href="https://en.wikipedia.org/wiki/Specific_impulse">Isp</a>:</strong> <a href="https://en.wikipedia.org/wiki/Specific_impulse">specific impulse</a>, expressed in seconds</li>
        <li><strong>Burn Duration:</strong> the period between the start and the end of burning process is called the burning duration, expressed in seconds.</li>
        <li><strong>Number of Chambers:</strong> number of <a href="https://en.wikipedia.org/wiki/Combustion_chamber">combustion chambers</a>.</li>
    </ul>
    <h2>Data</h2>
    <ul>
        <li><a href="{% url 'space_missions:engines-list' %}">Click here to view the list of engines.</a></li>
        <li><a href="{% url 'space_missions:engines-csv' %}">Click here to download the engine list in csv format.</a></li>
    </ul>
{% endblock %}

templates/space_missions/metadata/launch_mission.html
{% extends 'base.html' %}

{% block content %}
    <h1>Mission and Launch Metadata</h1>
    <ul>
        <li><strong>Name:</strong> the mission's identifier.</li>
        <li><strong>Launch ID:</strong> the launch identifier.</li>
        <li><strong>Date: </strong> the launch date, expressed in the format Mon-DD-YYYY</li>
        <li><strong>Organisation:</strong> identifier of the <a href="{% url 'space_missions:organisations' %}">organisation</a> that organised the launch</li>
        <li><strong>Vehicle:</strong> vehicle's identifier that refers to the <a href="{% url 'space_missions:launch-vehicles' %}">Launch Vehicle table</a></li>
        <li><strong>Astronauts: </strong> list of astronauts that participated in this missions, together with the following data:
            <ul>
                <li><em>Full Name:</em> the full name of the astronaut, more precisely "surname, name".</li>
                <li><em>Role: </em>string indicating the role of the astronaut in this particular mission.</li>
                <li><em>Join Year: </em> the year in which the astronaut joined the mission.</li>
            </ul>
        </li>
        <li><strong>Launch type:</strong> the type of launch, the possible values are 'Orbital', 'DeepSpaceMission' and 'unknown'</li>
        <li><strong>Success or Fail:</strong> field that can assume two values, 'success' or 'fail', that indicates whether the mission/launch has been a success or failure</li>
    </ul>
    <h2>Data</h2>
    <ul>
        <li><a href="{% url 'space_missions:missions-list' %}">Click here to view the full data (Mission+Launch+AstronautOccupations)</a></li>
        <li>To <em>download</em> the data in csv format, click:
            <ul>
                <li><a href="{% url 'space_missions:missions-csv' %}">here for the missions-launches table</a></li>
                <li><a href="{% url 'space_missions:astronautoccupations-csv' %}">here for the table of the astronauts occupations per mission.</a></li>
            </ul>
        </li>
    </ul>
{% endblock %}

templates/space_missions/metadata/launch_vehicle.html
{% extends 'base.html' %}

{% block content %}
    <h1>Vehicle metadata</h1>
    <ul>
        <li><strong>Name:</strong> vehicle name, given by its <a href="{% url 'space_missions:organisations' %}">manufacturer</a></li>
        <li><strong>Class:</strong> the vehicle type. It can be one of the following values:
            <ul>
                <li>Extraterrestrial Deep Space Launch</li>
                <li>Missile</li>
                <li>Orbital Vehicle</li>
                <li>Research Rocket</li>
                <li>Reentry Test Vehicle</li>
                <li>Exoatmospheric test</li>
                <li>Exoatmospheric weather rocket</li>
                <li>Endoatmospheric missile</li>
                <li>Cruise missile</li>
                <li>Endoatmospheric reentry test vehicle</li>
                <li>Endoatmospheric test/research</li>
                <li>Endoatmospheric Weather rocket</li>
            </ul>
        </li>
        <li><strong>Stages:</strong> set of stages that compose the vehicle.
            <ul>
                <li><em>Stage Name:</em> the identifier of the <a href="{% url 'space_missions:stages' %}">stage</a></li>
                <li><em>Stage Number:</em> integer from -1 to 6, indicating the sequence of stages, or the value '<a href="https://en.wikipedia.org/wiki/Payload_fairing">Fairing</a>'</li>
                <li><em>Dummy:</em> binary value 'yes' or 'no' indicating if it is a dummy stage or not.</li>
            </ul>
        </li>
        <li><strong>Manufacturer:</strong> <a href="{% url 'space_missions:organisations' %}">manufacturer</a> identifier.</li>
        <li><strong>Minimum number of stages:</strong> integer indicating the minimum number of stages supported by the vehicle</li>
        <li><strong>Maximum number of stages:</strong> integer indicating the maximum number of stages supported by the vehicle</li>
        <li><strong>Launch <a href="https://en.wikipedia.org/wiki/Mass">Mass</a>:</strong> the mass at the moment of launch, expressed in tons.</li>
        <li><strong><a href="https://en.wikipedia.org/wiki/Thrust">Thrust</a>:</strong> thrust expressed in kN</li>
        <li><strong><a href="https://en.wikipedia.org/wiki/Length">Length</a>:</strong> <a href="https://en.wikipedia.org/wiki/Length">length</a> in meters.</li>
        <li><strong><a href="https://en.wikipedia.org/wiki/Diameter">Diameter</a>:</strong> diameter in meters.</li>
    </ul>
    <h2>Data</h2>
    <ul>
        <li><a href="{% url 'space_missions:launch-vehicles-list' %}">Click here to view the full Launch Vehicles data.</a></li>
        <li>To <em>download</em> the data in csv format click:
            <ul>
                <li><a href="{% url 'space_missions:launchvehicles-csv' %}">here for the launch vehicle list.</a></li>
                <li><a href="{% url 'space_missions:vehiclestages-csv' %}">here for the vehicle-stages list.</a></li>
            </ul>
        </li>
    </ul>
{% endblock %}

templates/space_missions/metadata/organisation.html
{% extends 'base.html' %}

{% block content %}
    <h1>Organisation Metadata</h1>
    <ul>
        <li><strong>Name:</strong> organisation's full name.</li>
        <li><strong>Code:</strong> organisation's identifier.</li>
        <li><strong>Location:</strong> organisation's location.</li>
        <li><strong>Country:</strong> the identifier that referes to the <a href="{% url 'space_missions:countries' %}">country table</a>.</li>
        <li><strong>English name:</strong> the english name of the organisation.</li>
        <li><strong><a href="https://en.wikipedia.org/wiki/Longitude">Longitude</a>:</strong> the longitude coordinate of the organisation.</li>
        <li><strong><a href="https://en.wikipedia.org/wiki/Latitude">Latitude</a>:</strong> the latitude coordinate of the organisation.</li>
        <li><strong>Parent Organisation:</strong> the code of the parent organisation, can be empty.</li>
    </ul>
    <h2>Data</h2>
    <ul>
        <li>
            <a href="{% url 'space_missions:organisations-list' %}">Click here to view the organisation list.</a>
        </li>
        <li><a href="{% url 'space_missions:organisation-csv' %}">Click here to download the organisations table in csv format</a></li>
    </ul>
{% endblock %}

templates/space_missions/metadata/selection.html
{% extends 'base.html' %}

{% block content %}
    <h1>Selection Metadata</h1>
    <ul>
        <li><strong>Name:</strong> the selection's identifier.</li>
        <li><strong>Missions:</strong> list of missions identifiers for the particular selection procedure</li>
        <li><strong>Astronauts:</strong> list of astronauts that has been selected, together with the fields:
            <ul>
                <li>
                    <em>Name:</em> the astronaut name.
                </li>
                <li><em>Selections year:</em> the year of selection.</li>
            </ul>
        </li>
    </ul>
    <h2>Data</h2>
    <ul>
        <li>
            <a href="{% url 'space_missions:selections-list' %}">Click here to view the full data (selction+missions+astronauts)</a>
        </li>
        <li><a>To <em>download</em> the data in csv format, click:</a>
            <ul>
                <li>
                    <a href="{% url 'space_missions:selections-csv' %}">here for the selection-missions table;</a>
                </li>
                <li>
                    <a href="{% url 'space_missions:astroanutsselections-csv' %}">here for the selections-astronauts table.</a>
                </li>
            </ul>
        </li>
    </ul>
{% endblock %}

templates/space_missions/metadata/stage.html
{% extends 'base.html' %}

{% block content %}
    <h1>Stage Metadata</h1>
    <ul>
        <li><strong>Name:</strong> name of the vehicle, assigned by the <a href="{% url 'space_missions:organisations' %}">manufacturer</a>.</li>
        <li><strong>Manufacturer:</strong> <a href="{% url 'space_missions:organisations' %}">manufacturer</a>'s identifier.<em></em></li>
        <li><strong>Engine:</strong> <a href="{% url 'space_missions:engines' %}">engine</a>'s identifier.</li>
        <li><strong><a href="https://en.wikipedia.org/wiki/Length">Length</a>:</strong> <a href="https://en.wikipedia.org/wiki/Length">length</a> in meters.</li>
        <li><strong><a href="https://en.wikipedia.org/wiki/Diameter">Diameter</a>:</strong> diameter in meters.</li>
        <li><strong><a href="https://en.wikipedia.org/wiki/Vehicle_weight#Dry_weight">Dry Mass</a>:</strong> weight of a vehicle without any consumables, passengers, or cargo, in Kg.</li>
        <li><strong>Launch <a href="https://en.wikipedia.org/wiki/Mass">Mass</a>:</strong> the mass at the moment of launch, expressed in tonne.</li>
        <li><strong><a href="https://en.wikipedia.org/wiki/Thrust">Thrust</a>:</strong> thrust expressed in kN</li>
        <li><strong>Burn Duration:</strong> the period between the start and the end of burning process is called the burning duration, expressed in seconds.</li>
    </ul>
    <h2>Data</h2>
    <ul>
        <li><a href="{% url 'space_missions:stages-list' %}">Click here to view the Stage data.</a></li>
        <li><a href="{% url 'space_missions:stages-csv' %}">Click here to download the stages data in csv format.</a></li>
    </ul>
{% endblock %}