ODMC_exam_implementation/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

# Add URL maps to redirect the base URL to our application
from .views import HomePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home'),
    path('spacemissions/', include('space_missions.urls', namespace='space_missions')),
]

space_missions/urls.py
from django.urls import path
from . import views

app_name = 'space_missions'

urlpatterns = [
    path('countries-metadata/', views.CountryMetadata.as_view(), name='countries'),
    path('countries/', views.CountryList.as_view(), name='countries-list'),
    path('country/<int:pk>/', views.CountryDetail.as_view(), name='country-detail'),
    path('countries/download-csv', views.download_countries_csv, name='countries-csv'),
    path('astronauts-metadata/', views.AstronautMetadata.as_view(), name='astronauts'),
    path('astronauts/', views.AstronautList.as_view(), name='astronauts-list'),
    path('astronaut/<int:pk>/', views.AstronautDetail.as_view(), name='astronaut-detail'),
    path('astronauts/download-csv', views.download_astronauts_csv, name='astronauts-csv'),
    path('astronautsoccupations/download-csv', views.download_astronaut_occupations_csv, name='astronautoccupations-csv'),
    path('astronautsselections/download-csv', views.download_astronauts_selections_csv, name='astroanutsselections-csv'),
    path('organisations-metadata/', views.OrganisationMetadata.as_view(), name='organisations'),
    path('organisations/', views.OrganisationList.as_view(), name='organisations-list'),
    path('organisation/<int:pk>/', views.OrganisationDetail.as_view(), name='organisation-detail'),
    path('organisations/download-csv', views.download_organisations_csv, name='organisation-csv'),
    path('engines-metadata/', views.EngineMetadata.as_view(), name='engines'),
    path('engines/', views.EngineList.as_view(), name='engines-list'),
    path('engine/<int:pk>/', views.EngineDetail.as_view(), name='engine-detail'),
    path('engines/download-csv', views.download_engines_csv, name='engines-csv'),
    path('stages-metadata/', views.StageMetadata.as_view(), name='stages'),
    path('stages/', views.StageList.as_view(), name='stages-list'),
    path('stage/<int:pk>/', views.StageDetail.as_view(), name='stage-detail'),
    path('stages/download-csv', views.download_stages_csv, name='stages-csv'),
    path('launchvehicles-metadata/', views.LaunchVehicleMetadata.as_view(), name='launch-vehicles'),
    path('launchvehicles/', views.LaunchVehicleList.as_view(), name='launch-vehicles-list'),
    path('launchvehicle/<int:pk>/', views.LaunchVehicleDetail.as_view(), name='launch-vehicle-detail'),
    path('launchvehicles/download-csv', views.download_launch_vehicles_csv, name='launchvehicles-csv'),
    path('vehiclestages/download-csv', views.download_vehicle_stages_csv, name='vehiclestages-csv'),
    path('missions-launches-metadata/', views.MissionAndLaunchMetadata.as_view(), name='missions'),
    path('missions/', views.MissionList.as_view(), name='missions-list'),
    path('mission/<int:pk>/', views.MissionDetail.as_view(), name='mission-detail'),
    path('missions/download-csv', views.download_missions_csv, name='missions-csv'),
    path('selections-metadata/', views.SelectionMetadata.as_view(), name='selections'),
    path('selections/', views.SelectionList.as_view(), name='selections-list'),
    path('selection/<int:pk>/', views.SelectionDetail.as_view(), name='selection-detail'),
    path('selections/download-csv', views.download_selections_csv, name='selections-csv'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  {% block title %}<title>Space Missions</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300&display=swap" rel="stylesheet">

 
  <!-- Add additional CSS in static file -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a class="underlined" href="{% url 'home' %}"><h4>Home</h4></a></li>
          <li><a href="{% url 'space_missions:countries' %}"><h4>Countries</h4></a></li>
          <li><a href="{% url 'space_missions:astronauts' %}"><h4>Astronauts</h4></a></li>
            <li><a href="{% url 'space_missions:organisations' %}"><h4>Organisations</h4></a></li>
        <li><a href="{% url 'space_missions:engines' %}"><h4>Engines</h4></a></li>
        <li><a href="{% url 'space_missions:stages' %}"><h4>Stages</h4></a></li>
        <li><a href="{% url 'space_missions:launch-vehicles' %}"><h4>Launch Vehicles</h4></a></li>
        <li><a href="{% url 'space_missions:missions' %}"><h4>Missions</h4></a></li>
        <li><a href="{% url 'space_missions:selections' %}"><h4>Selections</h4></a></li>
        </ul>
        
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
  <footer>
    <p>Author: Eros Fabrici; email: <a href="mailto:eros.fabrici@gmail.com">eros.fabrici@gmail.com</a><br>
    Author: Paolo Pulcini; email: <a href="mailto:paoloearth@gmail.com">paoloearth@gmail.com</a><br>
      <a href="https://github.com/eferos93/ODMC_exam_implementation">GitHub repository</a></p>
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
  </footer>
<canvas id="canvas"></canvas>
</body>
<script type="text/javascript" src="{% static 'space_missions/js/master.js' %}">
</script>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

    <h1 style="text-align: center;" > <u><b> Space Missions </b></u></h1>
    <h3> Welcome to the home page! </h3>
    <p>This website contains data about Space Missions since the very first one.</p>
    <p>
        Following the links to the sources of data:
        <ul>
            <li><a href="http://www.planet4589.org/space/lvdb/index.html">JSR Launch Vehicle Database</a></li>
            <li><a href="https://data.mendeley.com/datasets/86tsnnbv2w/1">Astronaut database</a></li>
        </ul>
    </p>

{% endblock %}