ODMC_exam_implementation/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

# Add URL maps to redirect the base URL to our application
from .views import HomePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home'),
    path('spacemissions/', include('space_missions.urls', namespace='space_missions')),
]

space_missions/urls.py
from django.urls import path
from . import views

app_name = 'space_missions'

urlpatterns = [
    path('countries-metadata/', views.CountryMetadata.as_view(), name='countries'),
    path('countries/', views.CountryList.as_view(), name='countries-list'),
    path('country/<int:pk>/', views.CountryDetail.as_view(), name='country-detail'),
    path('countries/download-csv', views.download_countries_csv, name='countries-csv'),
    path('astronauts-metadata/', views.AstronautMetadata.as_view(), name='astronauts'),
    path('astronauts/', views.AstronautList.as_view(), name='astronauts-list'),
    path('astronaut/<int:pk>/', views.AstronautDetail.as_view(), name='astronaut-detail'),
    path('astronauts/download-csv', views.download_astronauts_csv, name='astronauts-csv'),
    path('astronautsoccupations/download-csv', views.download_astronaut_occupations_csv, name='astronautoccupations-csv'),
    path('astronautsselections/download-csv', views.download_astronauts_selections_csv, name='astroanutsselections-csv'),
    path('organisations-metadata/', views.OrganisationMetadata.as_view(), name='organisations'),
    path('organisations/', views.OrganisationList.as_view(), name='organisations-list'),
    path('organisation/<int:pk>/', views.OrganisationDetail.as_view(), name='organisation-detail'),
    path('organisations/download-csv', views.download_organisations_csv, name='organisation-csv'),
    path('engines-metadata/', views.EngineMetadata.as_view(), name='engines'),
    path('engines/', views.EngineList.as_view(), name='engines-list'),
    path('engine/<int:pk>/', views.EngineDetail.as_view(), name='engine-detail'),
    path('engines/download-csv', views.download_engines_csv, name='engines-csv'),
    path('stages-metadata/', views.StageMetadata.as_view(), name='stages'),
    path('stages/', views.StageList.as_view(), name='stages-list'),
    path('stage/<int:pk>/', views.StageDetail.as_view(), name='stage-detail'),
    path('stages/download-csv', views.download_stages_csv, name='stages-csv'),
    path('launchvehicles-metadata/', views.LaunchVehicleMetadata.as_view(), name='launch-vehicles'),
    path('launchvehicles/', views.LaunchVehicleList.as_view(), name='launch-vehicles-list'),
    path('launchvehicle/<int:pk>/', views.LaunchVehicleDetail.as_view(), name='launch-vehicle-detail'),
    path('launchvehicles/download-csv', views.download_launch_vehicles_csv, name='launchvehicles-csv'),
    path('vehiclestages/download-csv', views.download_vehicle_stages_csv, name='vehiclestages-csv'),
    path('missions-launches-metadata/', views.MissionAndLaunchMetadata.as_view(), name='missions'),
    path('missions/', views.MissionList.as_view(), name='missions-list'),
    path('mission/<int:pk>/', views.MissionDetail.as_view(), name='mission-detail'),
    path('missions/download-csv', views.download_missions_csv, name='missions-csv'),
    path('selections-metadata/', views.SelectionMetadata.as_view(), name='selections'),
    path('selections/', views.SelectionList.as_view(), name='selections-list'),
    path('selection/<int:pk>/', views.SelectionDetail.as_view(), name='selection-detail'),
    path('selections/download-csv', views.download_selections_csv, name='selections-csv'),
]

space_missions/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify


# Create your models here.

class Country(models.Model):
    class Meta:
        ordering = ['name']

    code = models.CharField(max_length=2, unique=True)
    name = models.CharField(max_length=40, null=True, blank=True)

    class Continent(models.TextChoices):
        AFRICA = 'Africa', _('Africa')
        AMERICAS = 'Americas', _('Americas')
        ASIA = 'Asia', _('Asia')
        EUROPE = 'Europe', _('Europe')
        OCEANIA = 'Oceania', _('Oceania')
        ANTARCTICA = 'Antarctica', _('Antarctica')

    continent = models.CharField(max_length=10, choices=Continent.choices, default=Continent.AMERICAS)

    def __str__(self):
        return self.name


class Astronaut(models.Model):
    class Meta:
        ordering = ['name']

    astronaut_id = models.CharField(max_length=256, unique=True)
    name = models.CharField(max_length=40)
    original_name = models.CharField(max_length=40)

    class SexOptions(models.TextChoices):
        MALE = 'M', _('Male')
        FEMALE = 'F', _('Female')
        UNSPECIFIED = 'U', _('Unspecified')

    class BackgroundOptions(models.TextChoices):
        MALE = 'M', _('Military')
        FEMALE = 'C', _('Civilian')
        UNSPECIFIED = 'U', _('Unspecified')

    sex = models.CharField(max_length=1, choices=SexOptions.choices, default=SexOptions.UNSPECIFIED)
    background = models.CharField(max_length=1, choices=BackgroundOptions.choices,
                                  default=BackgroundOptions.UNSPECIFIED)
    birth_year = models.PositiveSmallIntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2010)])
    nationality = models.ForeignKey('space_missions.Country', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name


class Selection(models.Model):
    class Meta:
        ordering = ['name']

    name = models.CharField(max_length=40, unique=True)
    missions = models.ManyToManyField('space_missions.Mission')
    astronauts = models.ManyToManyField('space_missions.Astronaut',
                                        through='AstronautSelection',
                                        related_name='selections')

    def __str__(self):
        return self.name


class AstronautSelection(models.Model):
    class Meta:
        unique_together = [('astronaut', 'selection', 'selection_year')]
        ordering = ['astronaut', 'selection']

    astronaut = models.ForeignKey('space_missions.Astronaut', on_delete=models.CASCADE)
    selection = models.ForeignKey('space_missions.Selection', on_delete=models.CASCADE)
    selection_year = models.PositiveSmallIntegerField(validators=[MinValueValidator(1900),
                                                                  MaxValueValidator(timezone.now().year)]
                                                      )

    def __str__(self):
        return 'Astronaut: ' + str(self.astronaut) + '; Selection: ' + str(self.selection)


class AstronautOccupation(models.Model):
    class Meta:
        unique_together = [('astronaut', 'mission', 'role', 'join_year')]
        ordering = ['astronaut', 'mission']

    astronaut = models.ForeignKey('space_missions.Astronaut', on_delete=models.CASCADE)
    mission = models.ForeignKey('space_missions.Mission', on_delete=models.CASCADE)
    role = models.CharField(max_length=40)
    join_year = models.PositiveSmallIntegerField(validators=[MinValueValidator(1900),
                                                             MaxValueValidator(timezone.now().year)]
                                                 )

    def __str__(self):
        return 'Astronaut: ' + str(self.astronaut) + '; Mission: ' + str(self.mission)


class Launch(models.Model):
    class Meta:
        ordering = ['launch_id']

    SF_choices = ('Success', 'Fail', 'unknown')
    launch_types = ('Orbital', 'DeepSpaceMission', 'unknown')

    launch_id = models.CharField(max_length=10, unique=True)
    date = models.DateField()
    launch_vehicle = models.ForeignKey('space_missions.LaunchVehicle', on_delete=models.SET_NULL, null=True, blank=True)
    organisation = models.ForeignKey('space_missions.Organisation', on_delete=models.SET_NULL, null=True, blank=True)
    success_or_fail = models.CharField(max_length=20, choices=[(d, d) for d in SF_choices])
    launch_type = models.CharField(max_length=20, choices=[(d, d) for d in launch_types])

    def __str__(self):
        return self.launch_id


class Mission(models.Model):
    class Meta:
        ordering = ['name']

    launch = models.OneToOneField('space_missions.Launch', on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=30, unique=True)
    astronauts = models.ManyToManyField('space_missions.Astronaut',
                                        blank=True,
                                        through='AstronautOccupation',
                                        related_name='missions')

    def __str__(self):
        return self.name


class LaunchVehicle(models.Model):
    class Meta:
        ordering = ['name']
    name = models.CharField(max_length=256, unique=True)
    min_stage = models.IntegerField(null=True, blank=True)
    max_stage = models.IntegerField(null=True, blank=True)
    launch_mass = models.FloatField(null=True, blank=True)
    TO_thrust = models.FloatField(null=True, blank=True)
    length = models.FloatField(null=True, blank=True)
    diameter = models.FloatField(null=True, blank=True)
    vehicle_classes = [
        ('D', 'Extraterrestrial Deep Space Launch'),
        ('M', 'Missile'),
        ('O', 'Orbital Vehicle'),
        ('R', 'Research Rocket'),
        ('V', 'Reentry Test Vehicle'),
        ('X', 'Exoatmospheric test'),
        ('Y', 'Exoatmospheric weather rocket'),
        ('A', 'Endoatmospheric missile'),
        ('C', 'Cruise missile'),
        ('Q', 'Endoatmospheric reentry test vehicle'),
        ('T', 'Endoatmospheric test/research'),
        ('W', 'Endoatmospheric Weather rocket')
    ]
    vehicle_class = models.CharField(max_length=1, choices=vehicle_classes, default='O')
    stages = models.ManyToManyField('space_missions.Stage', through='VehicleStage', blank=True)
    manufacturer = models.ForeignKey('space_missions.Organisation', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name


class Stage(models.Model):
    class Meta:
        ordering = ['name']

    name = models.CharField(max_length=256, unique=True)
    dry_mass = models.FloatField(null=True)
    launch_mass = models.FloatField(null=True)
    thrust = models.FloatField(null=True)
    burn_duration = models.FloatField(null=True)
    manufacturer = models.ForeignKey('space_missions.Organisation',
                                     on_delete=models.SET_NULL, null=True, blank=True)
    length = models.FloatField(null=True)
    diameter = models.FloatField(null=True)
    engine = models.ForeignKey('space_missions.Engine', on_delete=models.SET_NULL,
                               null=True, blank=True)

    def __str__(self):
        return self.name


class Engine(models.Model):
    class Meta:
        ordering = ['name']

    name = models.CharField(max_length=256, unique=True)
    manufacturer = models.ForeignKey('space_missions.Organisation', on_delete=models.SET_NULL, null=True, blank=True)
    mass = models.FloatField(null=True, blank=True)
    impulse = models.FloatField(null=True, blank=True)
    thrust = models.FloatField(null=True, blank=True)
    isp = models.FloatField(null=True, blank=True)
    burn_duration = models.FloatField(null=True, blank=True)
    chambers = models.PositiveSmallIntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


class VehicleStage(models.Model):
    class Meta:
        unique_together = [('launch_vehicle', 'stage', 'stage_number', 'dummy')]
        ordering = ['launch_vehicle', 'stage']
    launch_vehicle = models.ForeignKey('space_missions.LaunchVehicle', on_delete=models.CASCADE)
    stage = models.ForeignKey('space_missions.Stage', on_delete=models.CASCADE)
    stage_numbers = [
        ('-1', '-1'),
        ('0', '0'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('F', 'Fairing')
    ]
    stage_number = models.CharField(max_length=2, choices=stage_numbers)
    dummy = models.CharField(max_length=3, choices=[(value, value) for value in ['yes', 'no']])

    def __str__(self):
        return 'Vehicle: ' + str(self.launch_vehicle) + '; Stage: ' + str(self.stage)


class Organisation(models.Model):
    class Meta:
        ordering = ['name']

    code = models.CharField(max_length=256, unique=True)
    name = models.CharField(max_length=256, null=True)
    english_name = models.CharField(max_length=256, null=True)
    location = models.CharField(max_length=256, null=True)
    country = models.ForeignKey('space_missions.Country',
                                on_delete=models.SET_NULL, null=True, blank=True)
    longitude = models.FloatField(null=True)
    latitude = models.FloatField(null=True)
    parent_organisation = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name

templates/space_missions/astronaut_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>{{ astronaut.name }}'s details:</h1>
        <ul>
            <li><strong>Original Full Name: </strong>{{ astronaut.original_name }}</li>
            <li><strong>Birth year: </strong>{{ astronaut.birth_year }}</li>
            <li><strong>Sex: </strong>{{ astronaut.get_sex_display }}</li>
            <li><strong>Background: </strong>{{ astronaut.get_background_display }}</li>
            <li>
                <strong>Nationality</strong>
                {% if astronaut.nationality_id %}
                    <a href="{% url 'space_missions:country-detail' pk=astronaut.nationality.pk %}">
                        {{ astronaut.nationality.name }}
                    </a>
                {% endif %}
            </li>
        </ul>
    </div>
{% endblock %}

templates/space_missions/astronaut_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Astronauts List</h1>
{#    <form action='{% url 'space_missions:astronauts-csv' %}' method='GET'>#}
{#        <button type='submit'>Get astronauts.csv</button>#}
{#    </form>#}
{#    <form action='{% url 'space_missions:astronautoccupations-csv' %}' method='GET'>#}
{#        <button type='submit'>Get AstronautOccupations.csv</button>#}
{#    </form>#}
{#    <form action='{% url 'space_missions:astroanutsselections-csv' %}' method='GET'>#}
{#        <button type='submit'>Get AstronautSelections.csv</button>#}
{#    </form>#}
    {% if astronaut_list %}
        <ul>
            {% for astronaut in astronaut_list %}
                <li>
                    <a href="{% url 'space_missions:astronaut-detail' pk=astronaut.pk %}">
                        {{ astronaut.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% else %}
        <p>There is no Astronaut in the database</p>
    {% endif %}
{% endblock %}

templates/space_missions/engine_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Engine List</h1>
{#     <form action='{% url 'space_missions:engines-csv' %}' method='GET'>#}
{#        <button type='submit'>Get CSV</button>#}
{#     </form>#}
    {% if engine_list %}
        <ul>
            {% for engine in engine_list %}
                <li>
                    <a href="{% url 'space_missions:engine-detail' pk=engine.pk %}">
                        {{ engine.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
        <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% else %}
        <p>No engine found in the database!</p>
    {% endif %}
{% endblock %}

templates/space_missions/launchvehicle_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>{{ launchvehicle.name }}'s details:</h1>
        <ul>
            <li><strong>Class: </strong>{{ launchvehicle.get_vehicle_class_display }}</li>
            <li>
                <strong>Stages:</strong>
                {% if launchvehicle.vehiclestage_set.all %}
                    <ul>
                        {% for vehicle_stage in launchvehicle.vehiclestage_set.all %}
                            <li>
                                <em>Stage Name:</em> <a href="{% url 'space_missions:stage-detail' pk=vehicle_stage.stage_id %}">
                                    {{ vehicle_stage.stage.name }}
                                </a>;
                                <em>Stage Number:</em> {{ vehicle_stage.get_stage_number_display }};
                                <em>Dummy:</em> {{ vehicle_stage.dummy }}
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    Unknown
                {% endif %}
            </li>
            <li><strong>Manufacturer: </strong>
                {% if launchvehicle.manufacturer_id %}
                    <a href="{% url 'space_missions:organisation-detail' pk=launchvehicle.manufacturer_id %}">
                        {{ launchvehicle.manufacturer.name }}
                    </a>
                {% endif %}
            </li>
            <li><strong>Minimum number of stages: </strong>{{ launchvehicle.min_stage }}</li>
            <li><strong>Maximum number of stages: </strong>{{ launchvehicle.max_stage }}</li>
            <li><strong>Launch <a href="https://en.wikipedia.org/wiki/Mass">Mass</a>: </strong>{{ launchvehicle.launch_mass }} tons</li>
            <li><strong><a href="https://en.wikipedia.org/wiki/Thrust">Thrust</a>: </strong>{{ launch_vehcle.TO_thrust }} kN</li>
            <li><strong><a href="https://en.wikipedia.org/wiki/Length">Length</a>: </strong>{{ launchvehicle.length }} meters</li>
            <li><strong><a href="https://en.wikipedia.org/wiki/Diameter">Diameter</a>: </strong>{{ launchvehicle.diameter }} meters</li>
        </ul>
    </div>
{% endblock %}

templates/space_missions/launchvehicle_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Launch Vehicle List</h1>
{#    <form action='{% url 'space_missions:launchvehicles-csv' %}' method='GET'>#}
{#        <button type='submit'>Get LaunchVehicle.csv</button>#}
{#    </form>#}
{#    <form action='{% url 'space_missions:vehiclestages-csv' %}' method='GET'>#}
{#        <button type='submit'>Get VehicleStages.csv</button>#}
{#     </form>#}
    {% if launchvehicle_list %}
        <ul>
            {% for launch_vehicle in launchvehicle_list %}
                <li>
                    <a href="{% url 'space_missions:launch-vehicle-detail' pk=launch_vehicle.pk %}">
                        {{ launch_vehicle.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
        <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% else %}
        <p>No Vehicles found in the database!</p>
    {% endif %}
{% endblock %}

templates/space_missions/mission_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>{{ mission.name }}'s details:</h1>
        <ul>
            <li><strong>Launch ID: </strong>{{ mission.launch.launch_id }}</li>
            <li><strong>Date: </strong><time>{{ mission.launch.date }}</time></li>
            <li><strong>Organisation: </strong>
                {% if mission.launch.organisation_id %}
                    <a href="{% url 'space_missions:organisation-detail' pk=mission.launch.organisation_id %}">
                        {{ mission.launch.organisation.code }}
                    </a>
                {% endif %}
            </li>
            <li><strong>Vehicle: </strong>
                {% if mission.launch.launch_vehicle_id %}
                    <a href="{% url 'space_missions:launch-vehicle-detail' pk=mission.launch.launch_vehicle_id %}">
                        {{ mission.launch.launch_vehicle.name }}
                    </a>
                {% endif %}
            </li>
            <li>
                <strong>Astronauts:</strong>
                {% if mission.astronautoccupation_set.all %}
                    <ul>
                        {% for astronaut_occupation in mission.astronautoccupation_set.all %}
                            <li>
                                <em>Full Name:</em> <a href="{% url 'space_missions:astronaut-detail' pk=astronaut_occupation.astronaut_id %}">
                                    {{ astronaut_occupation.astronaut.name }}
                                </a>;
                                <em>Role:</em> {{ astronaut_occupation.role }};
                                <em>Join Year</em>: {{ astronaut_occupation.join_year }}
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    Unknown
                {% endif %}
            </li>
            <li><strong>Launch Type: </strong>{{ mission.launch.launch_type }}</li>
            <li><strong>Success or Fail: </strong>{{ mission.launch.success_or_fail }}</li>
        </ul>
    </div>
{% endblock %}

templates/space_missions/mission_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Mission List:</h1>
{#    <form action='{% url 'space_missions:missions-csv' %}' method='GET'>#}
{#        <button type='submit'>Get CSV</button>#}
    </form>
    {% if mission_list %}
        <ul>
            {% for mission in mission_list %}
                <li>
                    <a href="{% url 'space_missions:mission-detail' pk=mission.pk %}">
                        {{ mission.name }}, {{ mission.launch.launch_id }}
                    </a>
                </li>
            {% endfor %}
        </ul>
        <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% else %}
        <p>No Mission found in the database!</p>
    {% endif %}
{% endblock %}

templates/space_missions/organisation_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>{{ organisation.name }}'s details:</h1>
        <ul>
            <li><strong>Code: </strong> {{ organisation.code }}</li>
            <li><strong>English Name: </strong> {{ organisation.english_name }}</li>
            <li><strong>Location: </strong> {{ organisation.location }}</li>
            <li><strong>Country: </strong>
                {% if organisation.country_id %}
                    <a href="{% url 'space_missions:country-detail' pk=organisation.country_id %}">
                        {{ organisation.country.name }}
                    </a>
                {% endif %}
            </li>
            <li><strong><a href="https://en.wikipedia.org/wiki/Longitude">Longitude</a>: </strong> {{ organisation.longitude }}</li>
            <li><strong><a href="https://en.wikipedia.org/wiki/Latitude">Latitude</a>: </strong> {{ organisation.latitude }}</li>
            <li>
                <strong>Parent organisation: </strong>
                {% if organisation.parent_organisation_id %}
                    <a href="{% url 'space_missions:organisation-detail' pk=organisation.parent_organisation_id %}">
                        {{ organisation.parent_organisation.name }}
                    </a>
                {% endif %}
            </li>
        </ul>
    </div>
{% endblock %}

templates/space_missions/organisation_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Organisation List</h1>
{#    <form action='{% url 'space_missions:organisation-csv' %}' method='GET'>#}
{#        <button type='submit'>Get CSV</button>#}
{#    </form>#}
    {% if organisation_list %}
        <ul>
            {% for organisation in organisation_list %}
                <li>
                    <a href="{% url 'space_missions:organisation-detail' pk=organisation.pk %}">
                        {{ organisation.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
        <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% else %}
        <p>No organisation is stored in the database!</p>
    {% endif %}
{% endblock %}

templates/space_missions/selection_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>{{ selection.name }}'s details:</h1>
        <ul>
            <li>
                <strong>Missions:</strong>
                {% if selection.missions.all %}
                    <ul>
                        {% for mission in selection.missions.all %}
                            <li>
                                <a href="{% url 'space_missions:mission-detail' pk=mission.pk %}">
                                    {{ mission.name }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    Unknown
                {% endif %} 
            </li>
            <li>
                <strong>Astronauts:</strong>
                {% if selection.astronautselection_set.all %}
                    <ul>
                         {% for astronaut_selection in selection.astronautselection_set.all %}
                             <li>
                                 <em>Name:</em>
                                 <a href="{% url 'space_missions:astronaut-detail' pk=astronaut_selection.astronaut_id %}">
                                     {{ astronaut_selection.astronaut.name }}
                                 </a>;
                                 <em>Selection year:</em> {{ astronaut_selection.selection_year }}
                             </li>
                         {% endfor %}
                    </ul>
                {% else %}
                    Unknown
                {% endif %}
            </li>
        </ul>
    </div>
{% endblock %}

templates/space_missions/stage_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Stage List</h1>
{#    <form action='{% url 'space_missions:stages-csv' %}' method='GET'>#}
{#        <button type='submit'>Get CSV</button>#}
{#    </form>#}
    {% if stage_list %}
        <ul>
            {% for stage in stage_list %}
                <li><a href="{% url 'space_missions:stage-detail' pk=stage.pk %}">
                    {{ stage.name }}
                </a></li>
            {% endfor %}
        </ul>
        <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% else %}
        <p>No engines found in the database!</p>
    {% endif %}
{% endblock %}